# Site settings
title: Stay hungry . Stay foolish .
email: ironicstone@163.com
description: > # this means to ignore newlines until "baseurl:"
  Here is a blog for Wang YuJie , an angle for me , a secret garden for our own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ironicstone

# Build settings
markdown: kramdown
